# Generated by Django 3.1.2 on 2021-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_humidity', models.FloatField()),
                ('air_humidity', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('misurated_time', models.DateTimeField()),
            ],
        ),
    ]
