# Generated by Django 3.0.5 on 2020-11-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_humidity', models.FloatField()),
                ('air_humidity', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('misurated_time', models.DateField()),
            ],
        ),
    ]
