# Generated by Django 3.1.2 on 2021-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20201122_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
